[package]
name = "wasm_scratch"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = [ "cdylib" ]

[dependencies]
hashbrown.workspace = true
value = { workspace = true }
zmij = "1.0.14"

# dlmalloc = { version = "0.2.12", features = ["global"] }
# lol_alloc = "0.4.1"
talc = "4.4.3"
