[workspace]
members = [ "crates/*" ]

[package]
name = "luant"
version = "0.1.0"
edition = "2024"

[dependencies]
auto_impl = "1.3.0"
dumpster = "2.0.0"
fastrand = "2.3.0"
hashbrown = "0.16.1"
luant_lexer = { path = "crates/lexer" }
real_float = "0.3.0"
slotmap = "1.1.1"
strum = { version = "0.27.2", features = ["derive"] }
